version: '3.1'

services:

  app1:
    image: wordpress
    ports:
      - 8081:80
    volumes:
      - wp-content-uploads:/var/www/html/wp-content/uploads

  app2:
      image: wordpress
      ports:
        - 8082:80
      volumes:
        - wp-content-uploads:/var/www/html/wp-content/uploads
      depends_on:
        - app1

volumes:
  wp-content-uploads:
    driver: local
