version: '3.1'

services:

  app1:
    image: wordpress
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: DP_HOST
      WORDPRESS_DB_NAME: DB_NAME
      WORDPRESS_DB_USER: DB_USER
      WORDPRESS_DB_PASSWORD: DB_PASSWORD
    volumes:
      - wp-content-uploads:/var/www/html/wp-content/uploads

  app2:
      image: wordpress
      ports:
        - 8082:80
      environment:
        WORDPRESS_DB_HOST: DP_HOST
        WORDPRESS_DB_NAME: DB_NAME
        WORDPRESS_DB_USER: DB_USER
        WORDPRESS_DB_PASSWORD: DB_PASSWORD
      volumes:
        - wp-content-uploads:/var/www/html/wp-content/uploads
      depends_on:
        - app1

volumes:
  wp-content-uploads:
    driver: local
